# Generated by Django 5.2.4 on 2025-07-13 03:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Grid',
                'verbose_name_plural': 'Grids',
                'db_table': 'grids',
            },
        ),
        migrations.CreateModel(
            name='GridRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='energy.grid')),
            ],
            options={
                'verbose_name': 'Grid Region',
                'verbose_name_plural': 'Grid Regions',
                'db_table': 'grid_regions',
                'unique_together': {('grid', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GridNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='energy.gridregion')),
            ],
            options={
                'verbose_name': 'Grid Node',
                'verbose_name_plural': 'Grid Nodes',
                'db_table': 'grid_nodes',
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(-999999999.999), django.core.validators.MaxValueValidator(999999999.999)])),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='energy.gridnode')),
            ],
            options={
                'verbose_name': 'Measure',
                'verbose_name_plural': 'Measures',
                'db_table': 'measures',
                'indexes': [models.Index(fields=['node', 'timestamp', 'collected_at'], name='measures_node_id_8b707c_idx'), models.Index(fields=['timestamp', 'collected_at'], name='measures_timesta_a58e51_idx'), models.Index(fields=['node', 'timestamp'], name='measures_node_id_138947_idx')],
                'unique_together': {('node', 'timestamp', 'collected_at')},
            },
        ),
    ]
